### ISSUE TITLE
Should `some` return a `NonEmpty` instead of a list?

### ISSUE THREAD

**Issue by LightAndLight** [qfpl/papa#15]
I know it's nice that you can have mutually recursive definitions of `some` and `many`, but it seems more correct if the result of `some` is `NonEmpty`. Thoughts?

**Comment by tonymorris** [comment]
Yes, I wrote this function. It was originally in `semigroups` but has since been moved to `base`. It is called `some1`.

    λ> :m + Data.List.NonEmpty
    λ> :t some1
    some1 :: GHC.Base.Alternative f => f a -> f (NonEmpty a)
