### ISSUE TITLE
minimum, maximum

### ISSUE THREAD

**Issue by puffnfresh** [qfpl/papa#4]
```haskell
minimum, maximum :: (Foldable t, Ord a) => t a -> Maybe a
```

**Comment by tonymorris** [comment]
Yep. However, I think it should be:

    minimum, maximum :: (Foldable1 t, Ord a) => t a -> a

**Comment by puffnfresh** [comment]
@tonymorris I agree :+1:

**Comment by tonymorris** [comment]
Commit 140e1e36b7a214a9a647fef9f91d83a36dea964f
